const invitationDelete = [
	'abaci_admin',
	'zaair_admin',
	'zaair_assistant',
	'tenant_admin',
	'tenant_user',
	'abaci_admin',
	'tenant_employee',
];
export const disableAllowEntry = (details, userType) => {
	const Status = ['Scheduled', 'Delayed'];
	const IDtype = ['Other ID', 'Verified By Receptionist'];
	const ScanningDevice = ['Passport', 'Emirates ID'];
	const UserTypes = ['zaair_admin', 'zaair_receptionist', 'abaci_admin'];

	if (
		UserTypes.includes(userType) &&
		Status.includes(details?.status) &&
		(IDtype.includes(details?.visitor_id_type?.id_type) ||
			ScanningDevice.includes(details?.scanning_device))
	) {
		return true;
	}
	return false;
};

export const canDeleteInvitation = (state, createdUser, loggedUser) => {
	let flag = false;
	if (
		state === 'Scheduled' ||
		state === 'Delayed' ||
		state === 'No Show' ||
		state === 'Requested' ||
		state === 'Denied'
	) {
		if (invitationDelete.includes(loggedUser?.user_type)) {
			if (
				loggedUser?.user_type === 'tenant_user' &&
				createdUser?.user_type !== 'tenant_admin' &&
				createdUser?.user_type !== 'zaair_admin'
			) {
				flag = true;
			} else if (
				loggedUser?.user_type === 'tenant_employee' &&
				createdUser?.id === loggedUser?.id
			) {
				flag = true;
			} else if (
				loggedUser?.user_type === 'tenant_admin' &&
				(createdUser?.id === loggedUser?.id ||
					createdUser?.user_type === 'tenant_employee' ||
					createdUser?.user_type === 'tenant_user')
			) {
				flag = true;
			} else if (
				loggedUser?.user_type === 'zaair_admin' &&
				createdUser?.user_type === 'zaair_admin'
			) {
				flag = true;
			} else {
				flag = false;
			}
		}
	} else {
		flag = false;
	}

	return flag;
};

export const canEditVisitorDetailsfields = (field, loggedUser, InvitationState, visitorData) => {
	const zaairAdminFields = {
		'First name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Last name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Email: [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Contact No': [
			'Requested',
			'Scheduled',
			'Issued',
			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor ID type': [
			'Requested',
			'Scheduled',
			// 'Issued',
			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			'Approved',
		],
		'Visitor ID Details': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			'Approved',
		],
		'Visitor company name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Designation: [
			'Requested',
			'Scheduled',
			'Issued',
			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Tower: [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Company name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Office/Floor': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Host: [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected date': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected time': [
			'Requested',
			'Denied',
			// 'Arrived',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Approved',
		],
		Recurring: [
			'Requested',
			'Denied',
			// 'Arrived',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',

			// 'Approved',
		],
		'Pass validity date': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Pass validity time': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		DynamicFields: [
			'Requested',
			'Scheduled',
			'Issued',

			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Valid Days': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
	};
	// const zaairAdminFields_old = [
	// 	'First name',
	// 	'Last name',
	// 	'Email',
	// 	'Contact No',
	// 	// 'Visitor ID type',
	// 	// 'Visitor ID Details',
	// 	// 'Visitor company name',
	// 	// 'Designation',
	// 	'Tower',
	// 	'Company name',
	// 	'Office/Floor',
	// 	'Host',
	// 	'Expected date',
	// 	'Recurring',
	// 	'Pass validity date',
	// 	'DynamicFields',
	// 	'Valid Days',
	// ];

	const zaairReceptionistFields = {
		'First name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Last name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Email: [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Contact No': [
			'Requested',
			'Scheduled',
			'Issued',
			'Delayed',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor ID type': [
			'Requested',
			'Scheduled',
			'Delayed',
			'Approved',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
		],
		'Visitor ID Details': [
			// 'Requested',
			'Scheduled',
			// 'Issued',
			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			'Approved',
		],
		'Visitor company name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Designation: [
			'Requested',
			'Scheduled',
			'Issued',
			'Delayed',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Tower: [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Company name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Office/Floor': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Host: [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected date': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected time': [
			'Requested',
			'Denied',
			// 'Arrived',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Approved',
		],
		Recurring: [
			'Requested',
			'Denied',
			// 'Arrived',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',

			// 'Approved',
		],
		'Pass validity date': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Pass validity time': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		DynamicFields: [
			'Requested',
			'Scheduled',
			'Issued',
			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Valid Days': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
	};

	const companyAdminFields = {
		'First name': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Last name': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Email: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Contact No': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor ID type': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor ID Details': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor company name': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Designation: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Tower: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Company name': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Office/Floor': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Host: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected date': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected time': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Recurring: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Pass validity date': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Pass validity time': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		DynamicFields: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Valid Days': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
	};
	const companyUserFields = {
		'First name': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Last name': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Email: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Contact No': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor ID type': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor ID Details': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor company name': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Designation: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Tower: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Company name': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Office/Floor': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Host: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected date': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected time': [
			// 'Requested',
			'Scheduled',
			'Issued',
			'Entered',
			'Delayed',
			'Exited',
			'Expired',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			'Approved',
		],
		Recurring: [
			// 'Requested',
			'Scheduled',
			'Issued',
			'Entered',
			'Delayed',
			'Exited',
			'Expired',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			'Approved',
		],
		'Pass validity date': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Pass validity time': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Valid Days': [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		DynamicFields: [
			'Scheduled',
			'Delayed',
			// 'No Show',
			// 'Requested',
			// 'Issued',
			// 'Entered',
			// 'Exited',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
	};

	const companyEmployeeFields = {
		'First name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Last name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Email: [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Contact No': [
			'Requested',
			'Scheduled',
			'Issued',
			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor ID type': [
			'Requested',
			'Scheduled',
			// 'Issued',
			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor ID Details': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Visitor company name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Designation: [
			'Requested',
			'Scheduled',
			'Issued',
			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Tower: [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Company name': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Office/Floor': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		Host: [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected date': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Expected time': [
			'Requested',
			'Denied',
			// 'Arrived',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Approved',
		],
		Recurring: [
			'Requested',
			'Denied',
			// 'Arrived',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',

			// 'Approved',
		],
		'Pass validity date': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Pass validity time': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		DynamicFields: [
			'Requested',
			'Scheduled',
			'Issued',
			// 'Entered',
			'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
		'Valid Days': [
			// 'Requested',
			// 'Scheduled',
			// 'Issued',
			// 'Entered',
			// 'Delayed',
			// 'Exited',
			// 'No Show',
			// 'Denied',
			// 'Arrived',
			// 'Approved',
		],
	};

	const EventInvitation = [
		'First name',
		'Last name',
		'Email',
		'Contact No',
		'Visitor ID type',
		'Visitor ID Details',
		'Visitor company name',
		'Designation',
		// 'Tower',
		// 'Company name',
		// 'Office/Floor',
		// 'Host',
		// 'Expected date',
		// 'Expected time',
		// 'Recurring',
		// 'Pass validity date',
		// 'Pass validity time',
		// 'DynamicFields',
		// 'Valid Days',
	];

	if (
		visitorData?.entry_type !== 'Walk-in' &&
		(loggedUser?.id === visitorData?.created_by?.id ||
			loggedUser?.user_type === 'tenant_employee' ||
			loggedUser?.user_type === 'tenant_user' ||
			loggedUser?.user_type === 'tenant_admin') &&
		(InvitationState === 'Scheduled' || InvitationState === 'Requested')
	) {
		return false;
	}

	if (
		visitorData?.entry_type === 'Event' &&
		EventInvitation.includes(field) &&
		(loggedUser?.id === visitorData?.created_by?.id ||
			loggedUser?.user_type === 'zaair_admin' ||
			loggedUser?.user_type === 'tenant_admin')
	) {
		return false;
	}

	switch (loggedUser?.user_type) {
		case 'zaair_admin':
		case 'abaci_admin':
		case 'zaair_assistant':
			return (
				Object.prototype.hasOwnProperty.call(zaairAdminFields, field) &&
				!zaairAdminFields[field].includes(InvitationState)
				// zaairAdminFields.hasOwnProperty(field) &&
				// !zaairAdminFields[field].includes(InvitationState)
			);
		case 'zaair_receptionist':
			// return (
			// 	zaairReceptionistFields.hasOwnProperty(field) &&
			// 	!zaairReceptionistFields[field].includes(InvitationState)
			// );
			return (
				Object.prototype.hasOwnProperty.call(zaairReceptionistFields, field) &&
				!zaairReceptionistFields[field].includes(InvitationState)
			);

		case 'tenant_admin':
			return (
				Object.prototype.hasOwnProperty.call(companyAdminFields, field) &&
				!companyAdminFields[field].includes(InvitationState)
			);
		// return (
		// 	companyAdminFields.hasOwnProperty(field) &&
		// 	!companyAdminFields[field].includes(InvitationState)
		// );
		case 'tenant_user':
			return (
				Object.prototype.hasOwnProperty.call(companyUserFields, field) &&
				!companyUserFields[field].includes(InvitationState)
			);
		// return (
		// 	companyUserFields.hasOwnProperty(field) &&
		// 	!companyUserFields[field].includes(InvitationState)
		// );
		case 'tenant_employee':
			return (
				Object.prototype.hasOwnProperty.call(companyEmployeeFields, field) &&
				!companyEmployeeFields[field].includes(InvitationState)
			);
		// return (
		// 	companyEmployeeFields.hasOwnProperty(field) &&
		// 	!companyEmployeeFields[field].includes(InvitationState)
		// );

		default:
			return true;
	}
};
